# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-console" do
  name "aws-console"
  desc "Generate a temporary login URL for the AWS Console"
  homepage "https://github.com/joshdk/aws-console"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-console"

  on_macos do
    on_intel do
      url "https://github.com/joshdk/aws-console/releases/download/v#{version}/aws-console-darwin-amd64.tar.gz"
      sha256 "f03dc2b0c2271e75e5ca57761802e3c41a9fb9bd190d934247be85f7026cf6a5"
    end
    on_arm do
      url "https://github.com/joshdk/aws-console/releases/download/v#{version}/aws-console-darwin-arm64.tar.gz"
      sha256 "699476f7cdd7b0f795486f050c389130a38b543310b7c6b21b541a3e6af7b948"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/joshdk/aws-console/releases/download/v#{version}/aws-console-linux-amd64.tar.gz"
      sha256 "e6a98b075b07f37201c209ba461b17b4c353ee805ce20400453f761f63e8351d"
    end
    on_arm do
      url "https://github.com/joshdk/aws-console/releases/download/v#{version}/aws-console-linux-arm64.tar.gz"
      sha256 "693a13f5ca6769af6af4b8941d6c7b3dc982681ec24447465fb2c1db4f1ff4e8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-console"]
    end
  end

  # No zap stanza required
end
