# This file was generated by GoReleaser. DO NOT EDIT.
cask "krf" do
  name "krf"
  desc "Command line utility for filtering collections of Kubernetes resources"
  homepage "https://github.com/joshdk/krf"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "krf"

  on_macos do
    on_intel do
      url "https://github.com/joshdk/krf/releases/download/v#{version}/krf-darwin-amd64.tar.gz"
      sha256 "b5337e5b03e6d9fba4ad80a97232e1b59392ddf2ead6940cd62bd58edad44698"
    end
    on_arm do
      url "https://github.com/joshdk/krf/releases/download/v#{version}/krf-darwin-arm64.tar.gz"
      sha256 "10092c63a34e85eee12164380eb760022939eafd7571e8e490466d62ff74604e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/joshdk/krf/releases/download/v#{version}/krf-linux-amd64.tar.gz"
      sha256 "9f12285864bd058a6676e833146675ca4d9bd465b587e8c18cb3cf9dd735a332"
    end
    on_arm do
      url "https://github.com/joshdk/krf/releases/download/v#{version}/krf-linux-arm64.tar.gz"
      sha256 "9484865964a0dda8d065b233d801b605bbe5419f9358071aa19a80b75b762006"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/krf"]
    end
  end

  # No zap stanza required
end
