# This file was generated by GoReleaser. DO NOT EDIT.
cask "krf" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "f5438cc1e452f1d673432c573dab099258a5c2660d355889ab7122a4b0734f76"
      url "https://github.com/joshdk/krf/releases/download/v#{version}/krf-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "5dde7ae28c8e1004cb6b2555039f0c1188501ae75d7b391e0a4e2618c7e6ed9d"
      url "https://github.com/joshdk/krf/releases/download/v#{version}/krf-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c930bf74b7a53d748e4260b4bfa997963a280e544294e2fd72ecd0f772606214"
      url "https://github.com/joshdk/krf/releases/download/v#{version}/krf-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "24e8360ba0bed1f695890ec69ff51e2b2c4f9fe759cd6c73d49f9f4c75eb7a76"
      url "https://github.com/joshdk/krf/releases/download/v#{version}/krf-linux-amd64.tar.gz"
    end
  end

  name "krf"
  desc "Command line utility for filtering collections of Kubernetes resources"
  homepage "https://github.com/joshdk/krf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "krf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/krf"]
    end
  end

  # No zap stanza required
end
