# This file was generated by GoReleaser. DO NOT EDIT.
cask "krf" do
  name "krf"
  desc "Command line utility for filtering collections of Kubernetes resources"
  homepage "https://github.com/joshdk/krf"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "krf"

  on_macos do
    on_intel do
      url "https://github.com/joshdk/krf/releases/download/v#{version}/krf-darwin-amd64.tar.gz"
      sha256 "44e824744e3ce01e4f242a27c9b607fc75c323cae5a9a167d4538dc1f1da1266"
    end
    on_arm do
      url "https://github.com/joshdk/krf/releases/download/v#{version}/krf-darwin-arm64.tar.gz"
      sha256 "a9c18fb5d6f0a381c5bf5d5ae1d6fb222eaa149b2c7f7cff2c82d1c4b84a4329"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/joshdk/krf/releases/download/v#{version}/krf-linux-amd64.tar.gz"
      sha256 "dcca457d2a06b861278bc5c1cd9439c40cdb72ae8cf32fe68efe0b56c92d4a8d"
    end
    on_arm do
      url "https://github.com/joshdk/krf/releases/download/v#{version}/krf-linux-arm64.tar.gz"
      sha256 "b98920f325c5569e3d462b988e77517cd59ee478b7aa47da83d6ed0d24b485b0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/krf"]
    end
  end

  # No zap stanza required
end
