# This file was generated by GoReleaser. DO NOT EDIT.
cask "modfmt" do
  name "modfmt"
  desc "Formatter for go.mod and go.work files"
  homepage "https://github.com/joshdk/modfmt"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "modfmt"

  on_macos do
    on_intel do
      url "https://github.com/joshdk/modfmt/releases/download/v#{version}/modfmt-darwin-amd64.tar.gz"
      sha256 "a90f925b5fdac308a8118cb4b352fe460e08a22f876ee846d88cae8d515e67ac"
    end
    on_arm do
      url "https://github.com/joshdk/modfmt/releases/download/v#{version}/modfmt-darwin-arm64.tar.gz"
      sha256 "b480a984dfae742c3ed0f283fbc5f31dfb13e9d84c3f6faa727042bb3c9da5c1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/joshdk/modfmt/releases/download/v#{version}/modfmt-linux-amd64.tar.gz"
      sha256 "f09d5faabddbdc3bc9f541676c34d308d6d048fe2dd2e9d3f8411f60d166195a"
    end
    on_arm do
      url "https://github.com/joshdk/modfmt/releases/download/v#{version}/modfmt-linux-arm64.tar.gz"
      sha256 "54fd7d9faaddbe5cc741fd621c63ac636432cebac1351f9c29293aa15e687e84"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/modfmt"]
    end
  end

  # No zap stanza required
end
