# This file was generated by GoReleaser. DO NOT EDIT.
cask "modfmt" do
  name "modfmt"
  desc "Formatter for go.mod and go.work files"
  homepage "https://github.com/joshdk/modfmt"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "modfmt"

  on_macos do
    on_intel do
      url "https://github.com/joshdk/modfmt/releases/download/v#{version}/modfmt-darwin-amd64.tar.gz"
      sha256 "2529427c5be83731bd89cf6b47ad620c14555bc76c61f24722eac9aaa47ed496"
    end
    on_arm do
      url "https://github.com/joshdk/modfmt/releases/download/v#{version}/modfmt-darwin-arm64.tar.gz"
      sha256 "5f9b461b5ecd96cf129f465f01cf0e3bb170b1cff73f84901d89668d831820a2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/joshdk/modfmt/releases/download/v#{version}/modfmt-linux-amd64.tar.gz"
      sha256 "d9083a268ecd92bfb29c8e15d900d880ace825341e219e19f1e0cc372eef6223"
    end
    on_arm do
      url "https://github.com/joshdk/modfmt/releases/download/v#{version}/modfmt-linux-arm64.tar.gz"
      sha256 "ba6a960b905e206bda2e79ceb355354884c5d83256f26623102b0882044b7964"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/modfmt"]
    end
  end

  # No zap stanza required
end
