# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsConsole < Formula
  desc "Generate a temporary login URL for the AWS Console"
  homepage "https://github.com/joshdk/aws-console"
  version "0.1.1-rc.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joshdk/aws-console/releases/download/v0.1.1-rc.0/aws-console-darwin-amd64.tar.gz"
      sha256 "1490144ddd49472078120bd8e127a07583ebd8fec1f3611c185fab47882ba98f"

      def install
        bin.install "aws-console"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joshdk/aws-console/releases/download/v0.1.1-rc.0/aws-console-linux-amd64.tar.gz"
      sha256 "dc05a513b44b46788cae27dfdad7868837d52b231c265d91a1cd89925a76b02d"

      def install
        bin.install "aws-console"
      end
    end
  end

  def caveats; <<~EOS
    Run aws-console --help for usage
  EOS
  end

  test do
    system "#{bin}/aws-console --version"
  end
end
