# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsConsole < Formula
  desc "Generate a temporary login URL for the AWS Console"
  homepage "https://github.com/joshdk/aws-console"
  version "0.2.1-rc0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joshdk/aws-console/releases/download/v0.2.1-rc0/aws-console-darwin-amd64.tar.gz"
      sha256 "fe78d99e6866c636dbbd16b48ef3aeaaf30fb00fac2f67fccc4a7e25927f62fc"

      def install
        bin.install "aws-console"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joshdk/aws-console/releases/download/v0.2.1-rc0/aws-console-darwin-arm64.tar.gz"
      sha256 "5a82974984fcb28fc7782eeb609096f41630089c1d945e27a42538923121f3b1"

      def install
        bin.install "aws-console"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joshdk/aws-console/releases/download/v0.2.1-rc0/aws-console-linux-amd64.tar.gz"
      sha256 "bb714260ff23dbfb3160fb76a0748dbcd1d0b8aef7ac09864e82075cd9541023"

      def install
        bin.install "aws-console"
      end
    end
  end

  def caveats; <<~EOS
    Run aws-console --help for usage
  EOS
  end

  test do
    system "#{bin}/aws-console --version"
  end
end
