# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Retry < Formula
  desc "Rerun a command until it eventually succeeds, or doesn't"
  homepage "https://github.com/joshdk/retry"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joshdk/retry/releases/download/v1.3.1/retry-darwin-amd64.tar.gz"
      sha256 "a47db65869dcbdb27699a266cd4756d26548e795346884cf1e5d2045d1457202"

      def install
        bin.install "retry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joshdk/retry/releases/download/v1.3.1/retry-linux-amd64.tar.gz"
      sha256 "8a3141fefc99839e07c6d6757f622ea186d88b4f3f686db73f75418d4705a3cb"

      def install
        bin.install "retry"
      end
    end
  end

  def caveats; <<~EOS
    Run retry --help for usage
  EOS
  end

  test do
    system "#{bin}/retry -version"
  end
end
