# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Retry < Formula
  desc "Rerun a command until it eventually succeeds, or doesn't"
  homepage "https://github.com/joshdk/retry"
  version "1.3.0-rc2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joshdk/retry/releases/download/v1.3.0-rc2/retry-darwin-amd64.tar.gz"
      sha256 "6d28743598b96920836a1e8bebbec122a007fc4fc8d7925502c5ffa452cacfba"

      def install
        bin.install "retry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joshdk/retry/releases/download/v1.3.0-rc2/retry-linux-amd64.tar.gz"
      sha256 "743a985f77af26808dbeb406daced871d3b4296a64380cdb53edb8282292d33d"

      def install
        bin.install "retry"
      end
    end
  end

  def caveats; <<~EOS
    Run retry --help for usage
  EOS
  end

  test do
    system "#{bin}/retry -version"
  end
end
